<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<groupId>io.github.paulmarcelinbejan.toolbox</groupId>
		<artifactId>toolbox</artifactId>
		<version>1.0.3</version>
	</parent>
	
	<artifactId>toolbox-utils-validation</artifactId>
    <name>ToolBox Utils Validation</name>
    <packaging>jar</packaging>
	
	<dependencies>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
		</dependency>
		<dependency>
		    <groupId>commons-beanutils</groupId>
		    <artifactId>commons-beanutils</artifactId>
		    <exclusions>
			    <exclusion>
	                <groupId>commons-logging</groupId>
	                <artifactId>commons-logging</artifactId>
	            </exclusion>
	        </exclusions>
		</dependency>
		<dependency>
			<groupId>io.github.paulmarcelinbejan.toolbox</groupId>
			<artifactId>toolbox-utils-text</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.paulmarcelinbejan.toolbox</groupId>
			<artifactId>toolbox-exception</artifactId>
		</dependency>
	</dependencies>
	
</project>